
'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useUser } from '@/context/UserContext';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';
import { Loader2, PlayCircle, AlertTriangle } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import Link from 'next/link';
import type { GeneratedQuiz } from '@/types'; 

const ACTIVE_QUIZ_DATA_KEY = 'quizwhiz_active_quiz_data'; 
const QUIZ_SESSION_KEY = 'quizwhiz_current_quiz_session_data'; 

export default function QuizStartPage() {
  const router = useRouter();
  const { user, isLoading: userLoading } = useUser();
  const { toast } = useToast();
  const [isPreparingQuiz, setIsPreparingQuiz] = useState(false);
  const [activeQuizExistsOnLoad, setActiveQuizExistsOnLoad] = useState(false);
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
    if (typeof window !== 'undefined') {
      setActiveQuizExistsOnLoad(!!localStorage.getItem(ACTIVE_QUIZ_DATA_KEY));
    }
  }, []);

  const handleStartQuiz = async () => {
    if (!user) {
      toast({ title: 'Authentication Required', description: 'Please register or log in to start a quiz.', variant: 'destructive' });
      router.push('/register');
      return;
    }

    const activeQuizJson = localStorage.getItem(ACTIVE_QUIZ_DATA_KEY);
    if (!activeQuizJson) {
      toast({ title: 'No Quiz Available', description: 'An admin needs to upload a document and generate a quiz first.', variant: 'destructive' });
      setActiveQuizExistsOnLoad(false); 
      router.push('/admin/upload'); 
      return;
    }

    setIsPreparingQuiz(true);
    try {
      const quizDataFromStorage = JSON.parse(activeQuizJson) as GeneratedQuiz; 
      
      if (quizDataFromStorage && quizDataFromStorage.quiz && quizDataFromStorage.quiz.length > 0) {
        localStorage.setItem(QUIZ_SESSION_KEY, JSON.stringify(quizDataFromStorage));
        toast({ title: 'Quiz Ready!', description: `Your quiz with ${quizDataFromStorage.quiz.length} questions is ready.` });
        router.push('/quiz/play');
      } else {
        throw new Error('Stored quiz data is invalid or empty.');
      }
    } catch (error) {
      console.error('Error loading pre-generated quiz:', error);
      toast({
        title: 'Failed to Start Quiz',
        description: (error instanceof Error ? error.message : String(error)) || 'Could not load the pre-generated quiz. It might be corrupted or missing.',
        variant: 'destructive',
      });
      setIsPreparingQuiz(false);
    }
  };
  
  if (!isClient || userLoading) {
    return (
      <div className="flex justify-center items-center min-h-[60vh]">
        <Loader2 className="h-12 w-12 animate-spin text-primary" />
      </div>
    );
  }

  if (!user) {
    return (
      <Card className="w-full max-w-md mx-auto mt-10 text-center shadow-lg">
        <CardHeader>
          <CardTitle>Login Required</CardTitle> {/* font-headline applied via CardTitle component */}
          <CardDescription>You need to be logged in to start a quiz.</CardDescription>
        </CardHeader>
        <CardContent>
          <Button asChild>
            <Link href="/register">Register or Login</Link>
          </Button>
        </CardContent>
      </Card>
    );
  }

  if (!activeQuizExistsOnLoad) { 
     return (
      <Card className="w-full max-w-md mx-auto mt-10 text-center shadow-lg">
        <CardHeader>
          <CardTitle>No Quiz Available</CardTitle> {/* font-headline applied via CardTitle component */}
          <CardDescription>No quiz has been generated by an admin yet.</CardDescription>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground mb-4">Please ask an administrator to upload a document and generate a quiz.</p>
          <Button asChild variant="secondary">
            <Link href="/admin/upload">Admin Upload Page</Link>
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="flex flex-col items-center justify-center text-center space-y-6 py-10">
      <Card className="w-full max-w-lg shadow-xl p-8">
         <PlayCircle className="h-20 w-20 text-primary mx-auto mb-6" />
        <h1 className="text-4xl font-headline font-bold text-primary mb-4">Ready to Start?</h1>
        <p className="text-lg text-muted-foreground mb-8">
          The quiz is ready and based on the latest document uploaded by an administrator.
        </p>
        <Button onClick={handleStartQuiz} disabled={isPreparingQuiz} size="lg" className="w-full max-w-xs mx-auto">
          {isPreparingQuiz ? (
            <>
              <Loader2 className="mr-2 h-5 w-5 animate-spin" />
              Preparing Quiz...
            </>
          ) : (
            'Start Quiz Now'
          )}
        </Button>
        {isPreparingQuiz && (
          <p className="text-sm text-muted-foreground mt-4">Please wait, we're loading your questions...</p>
        )}

        <Card className="mt-8 bg-blue-50 border-blue-400 text-blue-700">
          <CardContent className="p-4 flex items-start space-x-3">
            <AlertTriangle className="h-5 w-5 mt-0.5 shrink-0 text-blue-500" />
            <div>
              <p className="text-sm font-semibold">Note:</p>
              <p className="text-xs">
                This quiz is based on the latest document(s) uploaded and processed by an administrator.
                Questions are selected during that processing step.
              </p>
            </div>
          </CardContent>
        </Card>
      </Card>
    </div>
  );
}
